"use client";

import React, { useState } from "react";
import { ChevronDown, HelpCircle, Sparkles } from "lucide-react";

const FAQS = [
  {
    question: "Can I monetize these AI videos on YouTube Shorts and the TikTok Creator Program?",
    answer:
      "Yes, 100%! All scripts generated by FacelessReels are uniquely written, all neural voices have full commercial broadcast clearance, and all 4K visual b-roll clips and background music tracks are royalty-free. Thousands of our creators are actively monetized in the YouTube Partner Program, TikTok Creator Rewards, and Instagram Bonus programs.",
  },
  {
    question: "How does the Auto-Scheduler connect to YouTube, Instagram, TikTok, and Email?",
    answer:
      "We use official API integrations (YouTube Data API v3, Meta Graph API, TikTok Content Posting API, and newsletter webhooks for Mailchimp, ConvertKit, Klaviyo, and Beehiiv). Once you authorize your accounts with 1-click OAuth, FacelessReels schedules, optimizes tags, and publishes at the best peak hours without you needing to open the apps.",
  },
  {
    question: "How does the Email Video Digest feature work for newsletters?",
    answer:
      "Email inboxes don't natively play heavy video files, so FacelessReels automatically generates lightweight animated looping GIF previews coupled with high-converting thumbnail cards and 1-click video links. You can copy the embed code or auto-sync with your email service provider to send video digests to your audience on autopilot.",
  },
  {
    question: "Can I edit the generated video, script, or caption styles before posting?",
    answer:
      "Yes! While FacelessReels can run 100% on autopilot, you also have full creative control. You can edit script lines, swap voices, change background b-roll scenes, customize caption font styles/colors (Hormozi, MrBeast, Cyberpunk), and drag-and-drop your scheduling calendar anytime.",
  },
  {
    question: "What languages and neural voices are supported?",
    answer:
      "FacelessReels supports 150+ neural voices across 40+ global languages including English, Spanish, Portuguese, German, French, Hindi, Japanese, Arabic, and more. You can even clone your own voice or custom brand voice in the Pro Growth and Agency tiers.",
  },
  {
    question: "Do I need video editing experience or a powerful computer?",
    answer:
      "Zero editing skills and zero heavy computer hardware required! All AI video rendering, voice generation, caption burning, and scheduling take place on our high-speed cloud GPU clusters. You can manage everything seamlessly from your browser or mobile phone.",
  },
  {
    question: "Is there a free trial to test the app?",
    answer:
      "Yes! You can create an account and generate 3 full reels free with zero credit card required. Test out our scriptwriter, voiceovers, captions, and auto-scheduler immediately.",
  },
];

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (idx: number) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <section id="faq" className="py-20 lg:py-28 relative bg-[#090a0f] overflow-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-purple-500/10 border border-purple-500/25 text-purple-300 text-xs font-semibold uppercase tracking-wider mb-4">
            <HelpCircle className="w-3.5 h-3.5 text-purple-400" />
            Got Questions?
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-white mb-4">
            Frequently Asked <span className="gradient-text-purple">Questions</span>
          </h2>
          <p className="text-base sm:text-lg text-slate-300">
            Everything you need to know about AI video generation, monetization compliance, and 4-channel auto-scheduling.
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {FAQS.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className={`rounded-2xl glass-card border transition-all duration-200 overflow-hidden ${
                  isOpen ? "border-purple-500/50 bg-white/[0.04]" : "border-white/10 hover:border-white/20"
                }`}
              >
                <button
                  onClick={() => toggle(idx)}
                  className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4 focus:outline-none"
                >
                  <span className="text-base font-semibold text-white">{faq.question}</span>
                  <div
                    className={`w-7 h-7 rounded-full bg-white/[0.05] flex items-center justify-center shrink-0 transition-transform duration-200 ${
                      isOpen ? "rotate-180 bg-purple-600/30 text-purple-300" : "text-slate-400"
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-5 sm:px-6 pb-6 text-xs sm:text-sm text-slate-300 leading-relaxed border-t border-white/5 pt-4 animate-in fade-in-50 duration-200">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Still have questions banner */}
        <div className="mt-12 text-center p-6 rounded-2xl glass-card border border-white/10">
          <p className="text-xs sm:text-sm text-slate-300 mb-3">
            Still have a question or need a custom enterprise fleet plan?
          </p>
          <a
            href="mailto:support@facelessreels.ai"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-purple-400 hover:text-purple-300 transition-colors"
          >
            <span>Chat with our 24/7 Creator Support Team</span> &rarr;
          </a>
        </div>
      </div>
    </section>
  );
}
